services:
  api:
    image: ghcr.io/evannotfound/vercount-api:edge
    env_file:
      - ./apps/api/.env
    environment:
      PORT: ${API_PORT:-8080}
      SCRIPT_PATH: ${SCRIPT_PATH:-}
    ports:
      - "${API_PORT:-8080}:8080"
    restart: unless-stopped
