services:
  api:
    image: ghcr.io/evannotfound/vercount-api:edge
    pull_policy: always
    environment:
      PORT: 8080
      REDIS_URL: ${REDIS_URL:-}
      DEBUG: ${DEBUG:-false}
      SCRIPT_PATH: ${SCRIPT_PATH:-}
    ports:
      - "${API_PORT:-8080}:8080"
    restart: unless-stopped
